# Generated by Django 5.1.2 on 2024-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_phrase', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('example_sentence', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
